version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Replace this with the runtime relevant to your project, e.g., 'nodejs', 'python', etc.
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker


  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 847245319109.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Current directory is $(pwd)
      - ls -l
      - echo Building the Docker image...
      - docker build -t test-core .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging the Docker image...
      - docker tag test-core:latest 847245319109.dkr.ecr.ap-south-1.amazonaws.com/test-core:latest
      - echo Pushing the Docker image to ECR...
      - docker push 847245319109.dkr.ecr.ap-south-1.amazonaws.com/test-core:latest

artifacts:
  files: '**/*'
  discard-paths: yes
